# Generated by Django 6.0.1 on 2026-02-06 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BibliotecaJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_atual",
                    models.CharField(
                        choices=[
                            ("QUERO", "Quero Jogar"),
                            ("JOGANDO", "Jogando"),
                            ("ZERADO", "Zerado"),
                            ("ABANDONADO", "Abandonei"),
                        ],
                        default="QUERO",
                        max_length=20,
                    ),
                ),
                ("avaliacao", models.IntegerField(blank=True, null=True)),
                ("review", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalogo.jogo"
                    ),
                ),
                (
                    "plataformas",
                    models.ManyToManyField(blank=True, to="catalogo.plataforma"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "jogo")},
            },
        ),
    ]
